import poochbotold.modules.windows.services as services

# fmt: off
WINDOWS_10_21H1_SERVICES = [
    services.Service("AarSvc_223ce0", "Agent Activation Runtime_223ce0", "Manual", "Stopped"),
    services.Service("AJRouter", "AllJoyn Router services.Service", "Manual", "Stopped"),
    services.Service("ALG", "Application Layer Gateway services.Service", "Manual", "Stopped"),
    services.Service("AppIDSvc", "Application Identity", "Manual", "Stopped"),
    services.Service("Appinfo", "Application Information", "Manual", "Running"),
    services.Service("AppMgmt", "Application Management", "Manual", "Stopped"),
    services.Service("AppReadiness", "App Readiness", "Manual", "Stopped"),
    services.Service("AppVClient", "Microsoft App-V Client", "Disabled", "Stopped"),
    services.Service("AppXSvc", "AppX Deployment services.Service (AppXSVC)", "Manual", "Stopped"),
    services.Service("AssignedAccessManagerSvc", "AssignedAccessManager services.Service", "Manual", "Stopped"),
    services.Service("AudioEndpointBuilder", "Windows Audio Endpoint Builder", "Automatic", "Running"),
    services.Service("Audiosrv", "Windows Audio", "Automatic", "Running"),
    services.Service("autotimesvc", "Cellular Time", "Manual", "Stopped"),
    services.Service("AxInstSV", "ActiveX Installer (AxInstSV)", "Manual", "Stopped"),
    services.Service("BcastDVRUserservices.Service_223ce0", "GameDVR and Broadcast User services.Service_223ce0", "Manual", "Stopped"),
    services.Service("BDESVC", "BitLocker Drive Encryption services.Service", "Manual", "Stopped"),
    services.Service("BFE", "Base Filtering Engine", "Automatic", "Running"),
    services.Service("BITS", "Background Intelligent Transfer services.Service", "Manual", "Stopped"),
    services.Service("BluetoothUserservices.Service_223ce0", "Bluetooth User Support services.Service_223ce0", "Manual", "Stopped"),
    services.Service("BrokerInfrastructure", "Background Tasks Infrastructure services.Service", "Automatic", "Running"),
    services.Service("BTAGservices.Service", "Bluetooth Audio Gateway services.Service", "Manual", "Running"),
    services.Service("BthAvctpSvc", "AVCTP service", "Manual", "Running"),
    services.Service("bthserv", "Bluetooth Support services.Service", "Manual", "Running"),
    services.Service("camsvc", "Capability Access Manager services.Service", "Manual", "Running"),
    services.Service("Captureservices.Service_223ce0", "Captureservices.Service_223ce0", "Manual", "Stopped"),
    services.Service("cbdhsvc_223ce0", "Clipboard User services.Service_223ce0", "Manual", "Running"),
    services.Service("CDPSvc", "Connected Devices Platform services.Service", "Automatic", "Running"),
    services.Service("CDPUserSvc_223ce0", "Connected Devices Platform User services.Service_223ce0", "Automatic", "Running"),
    services.Service("CertPropSvc", "Certificate Propagation", "Manual", "Stopped"),
    services.Service("ClipSVC", "Client License services.Service (ClipSVC)", "Manual", "Running"),
    services.Service("COMSysApp", "COM+ System Application", "Manual", "Stopped"),
    services.Service("ConsentUxUserSvc_223ce0", "ConsentUX_223ce0", "Manual", "Stopped"),
    services.Service("CoreMessagingRegistrar", "CoreMessaging", "Automatic", "Running"),
    services.Service("CredentialEnrollmentManagerUserSvc_223ce0", "CredentialEnrollmentManagerUserSvc_223ce0", "Manual", "Stopped"),
    services.Service("CryptSvc", "Cryptographic services.Services", "Automatic", "Running"),
    services.Service("Cscservices.Service", "Offline Files", "Manual", "Stopped"),
    services.Service("DcomLaunch", "DCOM Server Process Launcher", "Automatic", "Running"),
    services.Service("defragsvc", "Optimize drives", "Manual", "Stopped"),
    services.Service("DeviceAssociationBrokerSvc_223ce0", "DeviceAssociationBroker_223ce0", "Manual", "Stopped"),
    services.Service("DeviceAssociationservices.Service", "Device Association services.Service", "Manual", "Running"),
    services.Service("DeviceInstall", "Device Install services.Service", "Manual", "Running"),
    services.Service("DevicePickerUserSvc_223ce0", "DevicePicker_223ce0", "Manual", "Stopped"),
    services.Service("DevicesFlowUserSvc_223ce0", "DevicesFlow_223ce0", "Manual", "Stopped"),
    services.Service("DevQueryBroker", "DevQuery Background Discovery Broker", "Manual", "Stopped"),
    services.Service("Dhcp", "DHCP Client", "Automatic", "Running"),
    services.Service("diagnosticshub.standardcollector.service", "Microsoft (R) Diagnostics Hub Standard Collector services.Service", "Manual", "Stopped"),
    services.Service("diagsvc", "Diagnostic Execution services.Service", "Manual", "Stopped"),
    services.Service("DiagTrack", "Connected User Experiences and Telemetry", "Automatic", "Running"),
    services.Service("DialogBlockingservices.Service", "DialogBlockingservices.Service", "Disabled", "Stopped"),
    services.Service("DispBrokerDesktopSvc", "Display Policy services.Service", "Automatic", "Running"),
    services.Service("DisplayEnhancementservices.Service", "Display Enhancement services.Service", "Manual", "Running"),
    services.Service("DmEnrollmentSvc", "Device Management Enrollment services.Service", "Manual", "Stopped"),
    services.Service("dmwappushservice", "Device Management Wireless Application Protocol (WAP) Push message Routing services.Service", "Manual", "Stopped"),
    services.Service("Dnscache", "DNS Client", "Automatic", "Running"),
    services.Service("DoSvc", "Delivery Optimization", "Automatic", "Stopped"),
    services.Service("dot3svc", "Wired AutoConfig", "Manual", "Stopped"),
    services.Service("DPS", "Diagnostic Policy services.Service", "Automatic", "Running"),
    services.Service("DsmSvc", "Device Setup Manager", "Manual", "Stopped"),
    services.Service("DsSvc", "Data Sharing services.Service", "Manual", "Stopped"),
    services.Service("DusmSvc", "Data Usage", "Automatic", "Running"),
    services.Service("Eaphost", "Extensible Authentication Protocol", "Manual", "Stopped"),
    services.Service("edgeupdate", "Microsoft Edge Update services.Service (edgeupdate)", "Automatic", "Stopped"),
    services.Service("edgeupdatem", "Microsoft Edge Update services.Service (edgeupdatem)", "Manual", "Stopped"),
    services.Service("EFS", "Encrypting File System (EFS)", "Manual", "Stopped"),
    services.Service("embeddedmode", "Embedded Mode", "Manual", "Stopped"),
    services.Service("EntAppSvc", "Enterprise App Management services.Service", "Manual", "Stopped"),
    services.Service("EventLog", "Windows Event Log", "Automatic", "Running"),
    services.Service("EventSystem", "COM+ Event System", "Automatic", "Running"),
    services.Service("Fax", "Fax", "Manual", "Stopped"),
    services.Service("fdPHost", "Function Discovery Provider Host", "Manual", "Stopped"),
    services.Service("FDResPub", "Function Discovery Resource Publication", "Manual", "Stopped"),
    services.Service("fhsvc", "File History services.Service", "Manual", "Stopped"),
    services.Service("FontCache", "Windows Font Cache services.Service", "Automatic", "Running"),
    services.Service("FrameServer", "Windows Camera Frame Server", "Manual", "Stopped"),
    services.Service("gpsvc", "Group Policy Client", "Automatic", "Stopped"),
    services.Service("GraphicsPerfSvc", "GraphicsPerfSvc", "Manual", "Stopped"),
    services.Service("hidserv", "Human Interface Device services.Service", "Manual", "Stopped"),
    services.Service("HvHost", "HV Host services.Service", "Manual", "Stopped"),
    services.Service("icssvc", "Windows Mobile Hotspot services.Service", "Manual", "Stopped"),
    services.Service("IKEEXT", "IKE and AuthIP IPsec Keying Modules", "Manual", "Stopped"),
    services.Service("Installservices.Service", "Microsoft Store Install services.Service", "Manual", "Running"),
    services.Service("iphlpsvc", "IP Helper", "Automatic", "Running"),
    services.Service("IpxlatCfgSvc", "IP Translation Configuration services.Service", "Manual", "Stopped"),
    services.Service("KeyIso", "CNG Key Isolation", "Manual", "Running"),
    services.Service("KtmRm", "KtmRm for Distributed Transaction Coordinator", "Manual", "Stopped"),
    services.Service("LanmanServer", "Server", "Automatic", "Running"),
    services.Service("LanmanWorkstation", "Workstation", "Automatic", "Running"),
    services.Service("lfsvc", "Geolocation services.Service", "Manual", "Running"),
    services.Service("LicenseManager", "Windows License Manager services.Service", "Manual", "Running"),
    services.Service("lltdsvc", "Link-Layer Topology Discovery Mapper", "Manual", "Stopped"),
    services.Service("lmhosts", "TCP/IP NetBIOS Helper", "Manual", "Running"),
    services.Service("LSM", "Local Session Manager", "Automatic", "Running"),
    services.Service("LxpSvc", "Language Experience services.Service", "Manual", "Stopped"),
    services.Service("MapsBroker", "Downloaded Maps Manager", "Automatic", "Stopped"),
    services.Service("Messagingservices.Service_223ce0", "Messagingservices.Service_223ce0", "Manual", "Stopped"),
    services.Service("MicrosoftEdgeElevationservices.Service", "Microsoft Edge Elevation services.Service (MicrosoftEdgeElevationservices.Service)", "Manual", "Stopped"),
    services.Service("MixedRealityOpenXRSvc", "Windows Mixed Reality OpenXR services.Service", "Manual", "Stopped"),
    services.Service("mpssvc", "Windows Defender Firewall", "Automatic", "Running"),
    services.Service("MSDTC", "Distributed Transaction Coordinator", "Manual", "Stopped"),
    services.Service("MSiSCSI", "Microsoft iSCSI Initiator services.Service", "Manual", "Stopped"),
    services.Service("msiserver", "Windows Installer", "Manual", "Stopped"),
    services.Service("MsKeyboardFilter", "Microsoft Keyboard Filter", "Disabled", "Stopped"),
    services.Service("NaturalAuthentication", "Natural Authentication", "Manual", "Stopped"),
    services.Service("NcaSvc", "Network Connectivity Assistant", "Manual", "Stopped"),
    services.Service("Ncbservices.Service", "Network Connection Broker", "Manual", "Running"),
    services.Service("NcdAutoSetup", "Network Connected Devices Auto-Setup", "Manual", "Stopped"),
    services.Service("Netlogon", "Netlogon", "Manual", "Stopped"),
    services.Service("Netman", "Network Connections", "Manual", "Stopped"),
    services.Service("netprofm", "Network List services.Service", "Manual", "Running"),
    services.Service("NetSetupSvc", "Network Setup services.Service", "Manual", "Stopped"),
    services.Service("NetTcpPortSharing", "Net.Tcp Port Sharing services.Service", "Disabled", "Stopped"),
    services.Service("NgcCtnrSvc", "Microsoft Passport Container", "Manual", "Stopped"),
    services.Service("NgcSvc", "Microsoft Passport", "Manual", "Stopped"),
    services.Service("NlaSvc", "Network Location Awareness", "Automatic", "Running"),
    services.Service("nsi", "Network Store Interface services.Service", "Automatic", "Running"),
    services.Service("OneSyncSvc_223ce0", "Sync Host_223ce0", "Automatic", "Running"),
    services.Service("p2pimsvc", "Peer Networking Identity Manager", "Manual", "Stopped"),
    services.Service("p2psvc", "Peer Networking Grouping", "Manual", "Stopped"),
    services.Service("PcaSvc", "Program Compatibility Assistant services.Service", "Manual", "Running"),
    services.Service("PeerDistSvc", "BranchCache", "Manual", "Stopped"),
    services.Service("perceptionsimulation", "Windows Perception Simulation services.Service", "Manual", "Stopped"),
    services.Service("PerfHost", "Performance Counter DLL Host", "Manual", "Stopped"),
    services.Service("PhoneSvc", "Phone services.Service", "Manual", "Stopped"),
    services.Service("PimIndexMaintenanceSvc_223ce0", "Contact Data_223ce0", "Manual", "Running"),
    services.Service("pla", "Performance Logs & Alerts", "Manual", "Stopped"),
    services.Service("PlugPlay", "Plug and Play", "Manual", "Running"),
    services.Service("PNRPAutoReg", "PNRP Machine Name Publication services.Service", "Manual", "Stopped"),
    services.Service("PNRPsvc", "Peer Name Resolution Protocol", "Manual", "Stopped"),
    services.Service("PolicyAgent", "IPsec Policy Agent", "Manual", "Stopped"),
    services.Service("Power", "Power", "Automatic", "Running"),
    services.Service("PrintNotify", "Printer Extensions and Notifications", "Manual", "Stopped"),
    services.Service("PrintWorkflowUserSvc_223ce0", "PrintWorkflow_223ce0", "Manual", "Stopped"),
    services.Service("ProfSvc", "User Profile services.Service", "Automatic", "Running"),
    services.Service("PushToInstall", "Windows PushToInstall services.Service", "Manual", "Stopped"),
    services.Service("QWAVE", "Quality Windows Audio Video Experience", "Manual", "Stopped"),
    services.Service("RasAuto", "Remote Access Auto Connection Manager", "Manual", "Stopped"),
    services.Service("RasMan", "Remote Access Connection Manager", "Manual", "Stopped"),
    services.Service("RemoteAccess", "Routing and Remote Access", "Disabled", "Stopped"),
    services.Service("RemoteRegistry", "Remote Registry", "Disabled", "Stopped"),
    services.Service("RetailDemo", "Retail Demo services.Service", "Manual", "Stopped"),
    services.Service("RmSvc", "Radio Management services.Service", "Manual", "Stopped"),
    services.Service("RpcEptMapper", "RPC Endpoint Mapper", "Automatic", "Running"),
    services.Service("RpcLocator", "Remote Procedure Call (RPC) Locator", "Manual", "Stopped"),
    services.Service("RpcSs", "Remote Procedure Call (RPC)", "Automatic", "Running"),
    services.Service("SamSs", "Security Accounts Manager", "Automatic", "Running"),
    services.Service("SCardSvr", "Smart Card", "Manual", "Stopped"),
    services.Service("ScDeviceEnum", "Smart Card Device Enumeration services.Service", "Manual", "Stopped"),
    services.Service("Schedule", "Task Scheduler", "Automatic", "Running"),
    services.Service("SCPolicySvc", "Smart Card Removal Policy", "Manual", "Stopped"),
    services.Service("SDRSVC", "Windows Backup", "Manual", "Stopped"),
    services.Service("seclogon", "Secondary Logon", "Manual", "Stopped"),
    services.Service("SecurityHealthservices.Service", "Windows Security services.Service", "Manual", "Running"),
    services.Service("SEMgrSvc", "Payments and NFC/SE Manager", "Manual", "Running"),
    services.Service("SENS", "System Event Notification services.Service", "Automatic", "Running"),
    services.Service("Sense", "Windows Defender Advanced Threat Protection services.Service", "Manual", "Stopped"),
    services.Service("SensorDataservices.Service", "Sensor Data services.Service", "Manual", "Stopped"),
    services.Service("Sensorservices.Service", "Sensor services.Service", "Manual", "Running"),
    services.Service("SensrSvc", "Sensor Monitoring services.Service", "Manual", "Running"),
    services.Service("SessionEnv", "Remote Desktop Configuration", "Manual", "Stopped"),
    services.Service("SgrmBroker", "System Guard Runtime Monitor Broker", "Automatic", "Running"),
    services.Service("SharedAccess", "Internet Connection Sharing (ICS)", "Manual", "Stopped"),
    services.Service("SharedRealitySvc", "Spatial Data services.Service", "Manual", "Stopped"),
    services.Service("ShellHWDetection", "Shell Hardware Detection", "Automatic", "Running"),
    services.Service("shpamsvc", "Shared PC Account Manager", "Disabled", "Stopped"),
    services.Service("smphost", "Microsoft Storage Spaces SMP", "Manual", "Stopped"),
    services.Service("SmsRouter", "Microsoft Windows SMS Router services.Service.", "Manual", "Stopped"),
    services.Service("SNMPTRAP", "SNMP Trap", "Manual", "Stopped"),
    services.Service("spectrum", "Windows Perception services.Service", "Manual", "Stopped"),
    services.Service("Spooler", "Print Spooler", "Automatic", "Running"),
    services.Service("sppsvc", "Software Protection", "Automatic", "Stopped"),
    services.Service("SSDPSRV", "SSDP Discovery", "Manual", "Running"),
    services.Service("ssh-agent", "OpenSSH Authentication Agent", "Disabled", "Stopped"),
    services.Service("SstpSvc", "Secure Socket Tunneling Protocol services.Service", "Manual", "Stopped"),
    services.Service("StateRepository", "State Repository services.Service", "Manual", "Running"),
    services.Service("stisvc", "Windows Image Acquisition (WIA)", "Manual", "Stopped"),
    services.Service("StorSvc", "Storage services.Service", "Automatic", "Running"),
    services.Service("svsvc", "Spot Verifier", "Manual", "Stopped"),
    services.Service("swprv", "Microsoft Software Shadow Copy Provider", "Manual", "Stopped"),
    services.Service("SysMain", "SysMain", "Automatic", "Running"),
    services.Service("SystemEventsBroker", "System Events Broker", "Automatic", "Running"),
    services.Service("TabletInputservices.Service", "Touch Keyboard and Handwriting Panel services.Service", "Automatic", "Running"),
    services.Service("TapiSrv", "Telephony", "Manual", "Stopped"),
    services.Service("Termservices.Service", "Remote Desktop services.Services", "Manual", "Stopped"),
    services.Service("Themes", "Themes", "Automatic", "Running"),
    services.Service("TieringEngineservices.Service", "Storage Tiers Management", "Manual", "Stopped"),
    services.Service("TimeBrokerSvc", "Time Broker", "Manual", "Running"),
    services.Service("TokenBroker", "Web Account Manager", "Manual", "Running"),
    services.Service("TrkWks", "Distributed Link Tracking Client", "Automatic", "Running"),
    services.Service("TroubleshootingSvc", "Recommended Troubleshooting services.Service", "Manual", "Stopped"),
    services.Service("TrustedInstaller", "Windows Modules Installer", "Automatic", "Stopped"),
    services.Service("tzautoupdate", "Auto Time Zone Updater", "Disabled", "Stopped"),
    services.Service("UdkUserSvc_223ce0", "Udk User services.Service_223ce0", "Manual", "Stopped"),
    services.Service("UevAgentservices.Service", "User Experience Virtualization services.Service", "Disabled", "Stopped"),
    services.Service("UmRdpservices.Service", "Remote Desktop services.Services UserMode Port Redirector", "Manual", "Stopped"),
    services.Service("UnistoreSvc_223ce0", "User Data Storage_223ce0", "Manual", "Running"),
    services.Service("upnphost", "UPnP Device Host", "Manual", "Stopped"),
    services.Service("UserDataSvc_223ce0", "User Data Access_223ce0", "Manual", "Running"),
    services.Service("UserManager", "User Manager", "Automatic", "Running"),
    services.Service("UsoSvc", "Update Orchestrator services.Service", "Automatic", "Running"),
    services.Service("VacSvc", "Volumetric Audio Compositor services.Service", "Manual", "Stopped"),
    services.Service("VaultSvc", "Credential Manager", "Manual", "Running"),
    services.Service("vds", "Virtual Disk", "Manual", "Stopped"),
    services.Service("vmicguestinterface", "Hyper-V Guest services.Service Interface", "Manual", "Stopped"),
    services.Service("vmicheartbeat", "Hyper-V Heartbeat services.Service", "Manual", "Stopped"),
    services.Service("vmickvpexchange", "Hyper-V Data Exchange services.Service", "Manual", "Stopped"),
    services.Service("vmicrdv", "Hyper-V Remote Desktop Virtualization services.Service", "Manual", "Stopped"),
    services.Service("vmicshutdown", "Hyper-V Guest Shutdown services.Service", "Manual", "Stopped"),
    services.Service("vmictimesync", "Hyper-V Time Synchronization services.Service", "Manual", "Stopped"),
    services.Service("vmicvmsession", "Hyper-V PowerShell Direct services.Service", "Manual", "Stopped"),
    services.Service("vmicvss", "Hyper-V Volume Shadow Copy Requestor", "Manual", "Stopped"),
    services.Service("VSS", "Volume Shadow Copy", "Manual", "Stopped"),
    services.Service("W32Time", "Windows Time", "Manual", "Stopped"),
    services.Service("WaaSMedicSvc", "Windows Update Medic services.Service", "Manual", "Running"),
    services.Service("Walletservices.Service", "Walletservices.Service", "Manual", "Stopped"),
    services.Service("WarpJITSvc", "WarpJITSvc", "Manual", "Stopped"),
    services.Service("wbengine", "Block Level Backup Engine services.Service", "Manual", "Stopped"),
    services.Service("WbioSrvc", "Windows Biometric services.Service", "Manual", "Running"),
    services.Service("Wcmsvc", "Windows Connection Manager", "Automatic", "Running"),
    services.Service("wcncsvc", "Windows Connect Now - Config Registrar", "Manual", "Stopped"),
    services.Service("Wdiservices.ServiceHost", "Diagnostic services.Service Host", "Manual", "Running"),
    services.Service("WdiSystemHost", "Diagnostic System Host", "Manual", "Stopped"),
    services.Service("WdNisSvc", "Microsoft Defender Antivirus Network Inspection services.Service", "Manual", "Running"),
    services.Service("WebClient", "WebClient", "Manual", "Stopped"),
    services.Service("Wecsvc", "Windows Event Collector", "Manual", "Stopped"),
    services.Service("WEPHOSTSVC", "Windows Encryption Provider Host services.Service", "Manual", "Stopped"),
    services.Service("wercplsupport", "Problem Reports Control Panel Support", "Manual", "Stopped"),
    services.Service("WerSvc", "Windows Error Reporting services.Service", "Manual", "Stopped"),
    services.Service("WFDSConMgrSvc", "Wi-Fi Direct services.Services Connection Manager services.Service", "Manual", "Stopped"),
    services.Service("WiaRpc", "Still Image Acquisition Events", "Manual", "Stopped"),
    services.Service("WinDefend", "Microsoft Defender Antivirus services.Service", "Automatic", "Running"),
    services.Service("WinHttpAutoProxySvc", "WinHTTP Web Proxy Auto-Discovery services.Service", "Manual", "Running"),
    services.Service("Winmgmt", "Windows Management Instrumentation", "Automatic", "Running"),
    services.Service("WinRM", "Windows Remote Management (WS-Management)", "Manual", "Stopped"),
    services.Service("wisvc", "Windows Insider services.Service", "Manual", "Stopped"),
    services.Service("WlanSvc", "WLAN AutoConfig", "Manual", "Stopped"),
    services.Service("wlidsvc", "Microsoft Account Sign-in Assistant", "Manual", "Stopped"),
    services.Service("wlpasvc", "Local Profile Assistant services.Service", "Manual", "Stopped"),
    services.Service("WManSvc", "Windows Management services.Service", "Manual", "Stopped"),
    services.Service("wmiApSrv", "WMI Performance Adapter", "Manual", "Stopped"),
    services.Service("WMPNetworkSvc", "Windows Media Player Network Sharing services.Service", "Manual", "Stopped"),
    services.Service("workfolderssvc", "Work Folders", "Manual", "Stopped"),
    services.Service("WpcMonSvc", "Parental Controls", "Manual", "Stopped"),
    services.Service("WPDBusEnum", "Portable Device Enumerator services.Service", "Manual", "Stopped"),
    services.Service("Wpnservices.Service", "Windows Push Notifications System services.Service", "Automatic", "Running"),
    services.Service("WpnUserservices.Service_223ce0", "Windows Push Notifications User services.Service_223ce0", "Automatic", "Running"),
    services.Service("wscsvc", "Security Center", "Automatic", "Running"),
    services.Service("WSearch", "Windows Search", "Automatic", "Running"),
    services.Service("wuauserv", "Windows Update", "Manual", "Stopped"),
    services.Service("WwanSvc", "WWAN AutoConfig", "Manual", "Stopped"),
    services.Service("XblAuthManager", "Xbox Live Auth Manager", "Manual", "Stopped"),
    services.Service("XblGameSave", "Xbox Live Game Save", "Manual", "Stopped"),
    services.Service("XboxGipSvc", "Xbox Accessory Management services.Service", "Manual", "Stopped"),
    services.Service("XboxNetApiSvc", "Xbox Live Networking services.Service", "Manual", "Stopped")
]

WINDOWS_SERVER_2019_SERVICES = [
    services.Service("AJRouter", "AllJoyn Router services.Service", "Manual", "Stopped"),
    services.Service("ALG", "Application Layer Gateway services.Service", "Manual", "Stopped"),
    services.Service("AppIDSvc", "Application Identity", "Manual", "Stopped"),
    services.Service("Appinfo", "Application Information", "Manual", "Running"),
    services.Service("AppMgmt", "Application Management", "Manual", "Stopped"),
    services.Service("AppReadiness", "App Readiness", "Manual", "Stopped"),
    services.Service("AppVClient", "Microsoft App-V Client", "Disabled", "Stopped"),
    services.Service("AppXSvc", "AppX Deployment services.Service (AppXSVC)", "Manual", "Stopped"),
    services.Service("AudioEndpointBuilder", "Windows Audio Endpoint Builder", "Manual", "Stopped"),
    services.Service("Audiosrv", "Windows Audio", "Manual", "Stopped"),
    services.Service("AxInstSV", "ActiveX Installer (AxInstSV)", "Manual", "Stopped"),
    services.Service("BFE", "Base Filtering Engine", "Automatic", "Running"),
    services.Service("BITS", "Background Intelligent Transfer services.Service", "Manual", "Stopped"),
    services.Service("BrokerInfrastructure", "Background Tasks Infrastructure services.Service", "Automatic", "Running"),
    services.Service("BTAGservices.Service", "Bluetooth Audio Gateway services.Service", "Manual", "Stopped"),
    services.Service("BthAvctpSvc", "AVCTP service", "Manual", "Stopped"),
    services.Service("bthserv", "Bluetooth Support services.Service", "Manual", "Stopped"),
    services.Service("camsvc", "Capability Access Manager services.Service", "Manual", "Stopped"),
    services.Service("Captureservices.Service_f9adc", "Captureservices.Service_f9adc", "Manual", "Stopped"),
    services.Service("cbdhsvc_f9adc", "Clipboard User services.Service_f9adc", "Manual", "Stopped"),
    services.Service("CDPSvc", "Connected Devices Platform services.Service", "Automatic", "Running"),
    services.Service("CDPUserSvc_f9adc", "Connected Devices Platform User services.Service_f9adc", "Automatic", "Running"),
    services.Service("CertPropSvc", "Certificate Propagation", "Manual", "Stopped"),
    services.Service("ClipSVC", "Client License services.Service (ClipSVC)", "Manual", "Stopped"),
    services.Service("COMSysApp", "COM+ System Application", "Manual", "Stopped"),
    services.Service("ConsentUxUserSvc_f9adc", "ConsentUX_f9adc", "Manual", "Stopped"),
    services.Service("CoreMessagingRegistrar", "CoreMessaging", "Automatic", "Running"),
    services.Service("CryptSvc", "Cryptographic services.Services", "Automatic", "Running"),
    services.Service("Cscservices.Service", "Offline Files", "Disabled", "Stopped"),
    services.Service("DcomLaunch", "DCOM Server Process Launcher", "Automatic", "Running"),
    services.Service("defragsvc", "Optimize drives", "Manual", "Stopped"),
    services.Service("DeviceAssociationservices.Service", "Device Association services.Service", "Manual", "Stopped"),
    services.Service("DeviceInstall", "Device Install services.Service", "Manual", "Running"),
    services.Service("DevicePickerUserSvc_f9adc", "DevicePicker_f9adc", "Manual", "Stopped"),
    services.Service("DevicesFlowUserSvc_f9adc", "DevicesFlow_f9adc", "Manual", "Stopped"),
    services.Service("DevQueryBroker", "DevQuery Background Discovery Broker", "Manual", "Stopped"),
    services.Service("Dhcp", "DHCP Client", "Automatic", "Running"),
    services.Service("diagnosticshub.standardcollector.service", "Microsoft (R) Diagnostics Hub Standard Collector services.Service", "Manual", "Stopped"),
    services.Service("DiagTrack", "Connected User Experiences and Telemetry", "Automatic", "Running"),
    services.Service("DmEnrollmentSvc", "Device Management Enrollment services.Service", "Manual", "Stopped"),
    services.Service("dmwappushservice", "Device Management Wireless Application Protocol (WAP) Push message Routing services.Service", "Manual", "Stopped"),
    services.Service("Dnscache", "DNS Client", "Automatic", "Running"),
    services.Service("DoSvc", "Delivery Optimization", "Manual", "Stopped"),
    services.Service("dot3svc", "Wired AutoConfig", "Manual", "Stopped"),
    services.Service("DPS", "Diagnostic Policy services.Service", "Automatic", "Running"),
    services.Service("DsmSvc", "Device Setup Manager", "Manual", "Stopped"),
    services.Service("DsSvc", "Data Sharing services.Service", "Manual", "Stopped"),
    services.Service("Eaphost", "Extensible Authentication Protocol", "Manual", "Stopped"),
    services.Service("EFS", "Encrypting File System (EFS)", "Manual", "Stopped"),
    services.Service("embeddedmode", "Embedded Mode", "Manual", "Stopped"),
    services.Service("EntAppSvc", "Enterprise App Management services.Service", "Manual", "Stopped"),
    services.Service("EventLog", "Windows Event Log", "Automatic", "Running"),
    services.Service("EventSystem", "COM+ Event System", "Automatic", "Running"),
    services.Service("fdPHost", "Function Discovery Provider Host", "Manual", "Running"),
    services.Service("FDResPub", "Function Discovery Resource Publication", "Manual", "Running"),
    services.Service("FontCache", "Windows Font Cache services.Service", "Automatic", "Running"),
    services.Service("FrameServer", "Windows Camera Frame Server", "Manual", "Stopped"),
    services.Service("gpsvc", "Group Policy Client", "Automatic", "Running"),
    services.Service("GraphicsPerfSvc", "GraphicsPerfSvc", "Manual", "Stopped"),
    services.Service("hidserv", "Human Interface Device services.Service", "Manual", "Stopped"),
    services.Service("HvHost", "HV Host services.Service", "Manual", "Stopped"),
    services.Service("icssvc", "Windows Mobile Hotspot services.Service", "Manual", "Stopped"),
    services.Service("IKEEXT", "IKE and AuthIP IPsec Keying Modules", "Manual", "Stopped"),
    services.Service("Installservices.Service", "Microsoft Store Install services.Service", "Manual", "Stopped"),
    services.Service("iphlpsvc", "IP Helper", "Automatic", "Running"),
    services.Service("KeyIso", "CNG Key Isolation", "Manual", "Running"),
    services.Service("KPSSVC", "KDC Proxy Server service (KPS)", "Manual", "Stopped"),
    services.Service("KtmRm", "KtmRm for Distributed Transaction Coordinator", "Manual", "Stopped"),
    services.Service("LanmanServer", "Server", "Automatic", "Running"),
    services.Service("LanmanWorkstation", "Workstation", "Automatic", "Running"),
    services.Service("lfsvc", "Geolocation services.Service", "Manual", "Stopped"),
    services.Service("LicenseManager", "Windows License Manager services.Service", "Manual", "Running"),
    services.Service("lltdsvc", "Link-Layer Topology Discovery Mapper", "Manual", "Stopped"),
    services.Service("lmhosts", "TCP/IP NetBIOS Helper", "Manual", "Running"),
    services.Service("LSM", "Local Session Manager", "Automatic", "Running"),
    services.Service("MapsBroker", "Downloaded Maps Manager", "Automatic", "Stopped"),
    services.Service("mpssvc", "Windows Defender Firewall", "Automatic", "Running"),
    services.Service("MSDTC", "Distributed Transaction Coordinator", "Automatic", "Running"),
    services.Service("MSiSCSI", "Microsoft iSCSI Initiator services.Service", "Manual", "Stopped"),
    services.Service("msiserver", "Windows Installer", "Manual", "Stopped"),
    services.Service("NcaSvc", "Network Connectivity Assistant", "Manual", "Stopped"),
    services.Service("Ncbservices.Service", "Network Connection Broker", "Manual", "Running"),
    services.Service("Netlogon", "Netlogon", "Manual", "Stopped"),
    services.Service("Netman", "Network Connections", "Manual", "Stopped"),
    services.Service("netprofm", "Network List services.Service", "Manual", "Running"),
    services.Service("NetSetupSvc", "Network Setup services.Service", "Manual", "Stopped"),
    services.Service("NetTcpPortSharing", "Net.Tcp Port Sharing services.Service", "Disabled", "Stopped"),
    services.Service("NgcCtnrSvc", "Microsoft Passport Container", "Manual", "Stopped"),
    services.Service("NgcSvc", "Microsoft Passport", "Manual", "Stopped"),
    services.Service("NlaSvc", "Network Location Awareness", "Automatic", "Running"),
    services.Service("nsi", "Network Store Interface services.Service", "Automatic", "Running"),
    services.Service("PcaSvc", "Program Compatibility Assistant services.Service", "Manual", "Running"),
    services.Service("PerfHost", "Performance Counter DLL Host", "Manual", "Stopped"),
    services.Service("PhoneSvc", "Phone services.Service", "Manual", "Stopped"),
    services.Service("PimIndexMaintenanceSvc_f9adc", "Contact Data_f9adc", "Manual", "Stopped"),
    services.Service("pla", "Performance Logs & Alerts", "Manual", "Stopped"),
    services.Service("PlugPlay", "Plug and Play", "Manual", "Running"),
    services.Service("PolicyAgent", "IPsec Policy Agent", "Manual", "Stopped"),
    services.Service("Power", "Power", "Automatic", "Running"),
    services.Service("PrintNotify", "Printer Extensions and Notifications", "Manual", "Stopped"),
    services.Service("PrintWorkflowUserSvc_f9adc", "PrintWorkflow_f9adc", "Manual", "Stopped"),
    services.Service("ProfSvc", "User Profile services.Service", "Automatic", "Running"),
    services.Service("PushToInstall", "Windows PushToInstall services.Service", "Manual", "Stopped"),
    services.Service("QWAVE", "Quality Windows Audio Video Experience", "Manual", "Stopped"),
    services.Service("RasAuto", "Remote Access Auto Connection Manager", "Manual", "Stopped"),
    services.Service("RasMan", "Remote Access Connection Manager", "Manual", "Stopped"),
    services.Service("RemoteAccess", "Routing and Remote Access", "Disabled", "Stopped"),
    services.Service("RemoteRegistry", "Remote Registry", "Automatic", "Stopped"),
    services.Service("RmSvc", "Radio Management services.Service", "Manual", "Stopped"),
    services.Service("RpcEptMapper", "RPC Endpoint Mapper", "Automatic", "Running"),
    services.Service("RpcLocator", "Remote Procedure Call (RPC) Locator", "Manual", "Stopped"),
    services.Service("RpcSs", "Remote Procedure Call (RPC)", "Automatic", "Running"),
    services.Service("RSoPProv", "Resultant Set of Policy Provider", "Manual", "Stopped"),
    services.Service("sacsvr", "Special Administration Console Helper", "Manual", "Stopped"),
    services.Service("SamSs", "Security Accounts Manager", "Automatic", "Running"),
    services.Service("SCardSvr", "Smart Card", "Manual", "Stopped"),
    services.Service("ScDeviceEnum", "Smart Card Device Enumeration services.Service", "Manual", "Stopped"),
    services.Service("Schedule", "Task Scheduler", "Automatic", "Running"),
    services.Service("SCPolicySvc", "Smart Card Removal Policy", "Manual", "Stopped"),
    services.Service("seclogon", "Secondary Logon", "Manual", "Stopped"),
    services.Service("SecurityHealthservices.Service", "Windows Security services.Service", "Manual", "Stopped"),
    services.Service("SEMgrSvc", "Payments and NFC/SE Manager", "Manual", "Stopped"),
    services.Service("SENS", "System Event Notification services.Service", "Automatic", "Running"),
    services.Service("Sense", "Windows Defender Advanced Threat Protection services.Service", "Manual", "Stopped"),
    services.Service("SensorDataservices.Service", "Sensor Data services.Service", "Manual", "Stopped"),
    services.Service("Sensorservices.Service", "Sensor services.Service", "Manual", "Stopped"),
    services.Service("SensrSvc", "Sensor Monitoring services.Service", "Manual", "Stopped"),
    services.Service("SessionEnv", "Remote Desktop Configuration", "Manual", "Stopped"),
    services.Service("SgrmBroker", "System Guard Runtime Monitor Broker", "Manual", "Stopped"),
    services.Service("SharedAccess", "Internet Connection Sharing (ICS)", "Manual", "Stopped"),
    services.Service("ShellHWDetection", "Shell Hardware Detection", "Automatic", "Running"),
    services.Service("shpamsvc", "Shared PC Account Manager", "Disabled", "Stopped"),
    services.Service("smphost", "Microsoft Storage Spaces SMP", "Manual", "Stopped"),
    services.Service("SNMPTRAP", "SNMP Trap", "Manual", "Stopped"),
    services.Service("Spooler", "Print Spooler", "Automatic", "Running"),
    services.Service("sppsvc", "Software Protection", "Automatic", "Stopped"),
    services.Service("SSDPSRV", "SSDP Discovery", "Disabled", "Stopped"),
    services.Service("ssh-agent", "OpenSSH Authentication Agent", "Disabled", "Stopped"),
    services.Service("SstpSvc", "Secure Socket Tunneling Protocol services.Service", "Manual", "Stopped"),
    services.Service("StateRepository", "State Repository services.Service", "Manual", "Running"),
    services.Service("stisvc", "Windows Image Acquisition (WIA)", "Manual", "Stopped"),
    services.Service("StorSvc", "Storage services.Service", "Manual", "Running"),
    services.Service("svsvc", "Spot Verifier", "Manual", "Stopped"),
    services.Service("swprv", "Microsoft Software Shadow Copy Provider", "Manual", "Stopped"),
    services.Service("SysMain", "SysMain", "Automatic", "Running"),
    services.Service("SystemEventsBroker", "System Events Broker", "Automatic", "Running"),
    services.Service("TabletInputservices.Service", "Touch Keyboard and Handwriting Panel services.Service", "Manual", "Running"),
    services.Service("tapisrv", "Telephony", "Manual", "Stopped"),
    services.Service("Termservices.Service", "Remote Desktop services.Services", "Manual", "Stopped"),
    services.Service("Themes", "Themes", "Automatic", "Running"),
    services.Service("TieringEngineservices.Service", "Storage Tiers Management", "Manual", "Stopped"),
    services.Service("TimeBrokerSvc", "Time Broker", "Manual", "Running"),
    services.Service("TokenBroker", "Web Account Manager", "Manual", "Running"),
    services.Service("TrkWks", "Distributed Link Tracking Client", "Automatic", "Running"),
    services.Service("TrustedInstaller", "Windows Modules Installer", "Manual", "Stopped"),
    services.Service("tzautoupdate", "Auto Time Zone Updater", "Disabled", "Stopped"),
    services.Service("UALSVC", "User Access Logging services.Service", "Automatic", "Running"),
    services.Service("UevAgentservices.Service", "User Experience Virtualization services.Service", "Disabled", "Stopped"),
    services.Service("UmRdpservices.Service", "Remote Desktop services.Services UserMode Port Redirector", "Manual", "Stopped"),
    services.Service("UnistoreSvc_f9adc", "User Data Storage_f9adc", "Manual", "Stopped"),
    services.Service("upnphost", "UPnP Device Host", "Disabled", "Stopped"),
    services.Service("UserDataSvc_f9adc", "User Data Access_f9adc", "Manual", "Stopped"),
    services.Service("UserManager", "User Manager", "Automatic", "Running"),
    services.Service("UsoSvc", "Update Orchestrator services.Service", "Automatic", "Running"),
    services.Service("VaultSvc", "Credential Manager", "Manual", "Running"),
    services.Service("vds", "Virtual Disk", "Manual", "Stopped"),
    services.Service("VM3Dservices.Service", "VMware SVGA Helper services.Service", "Automatic", "Running"),
    services.Service("vmicguestinterface", "Hyper-V Guest services.Service Interface", "Manual", "Stopped"),
    services.Service("vmicheartbeat", "Hyper-V Heartbeat services.Service", "Manual", "Stopped"),
    services.Service("vmickvpexchange", "Hyper-V Data Exchange services.Service", "Manual", "Stopped"),
    services.Service("vmicrdv", "Hyper-V Remote Desktop Virtualization services.Service", "Manual", "Stopped"),
    services.Service("vmicshutdown", "Hyper-V Guest Shutdown services.Service", "Manual", "Stopped"),
    services.Service("vmictimesync", "Hyper-V Time Synchronization services.Service", "Manual", "Stopped"),
    services.Service("vmicvmsession", "Hyper-V PowerShell Direct services.Service", "Manual", "Stopped"),
    services.Service("vmicvss", "Hyper-V Volume Shadow Copy Requestor", "Manual", "Stopped"),
    services.Service("VSS", "Volume Shadow Copy", "Manual", "Stopped"),
    services.Service("W32Time", "Windows Time", "Automatic", "Running"),
    services.Service("WaaSMedicSvc", "Windows Update Medic services.Service", "Manual", "Stopped"),
    services.Service("Walletservices.Service", "Walletservices.Service", "Manual", "Stopped"),
    services.Service("WarpJITSvc", "WarpJITSvc", "Manual", "Stopped"),
    services.Service("WbioSrvc", "Windows Biometric services.Service", "Manual", "Stopped"),
    services.Service("Wcmsvc", "Windows Connection Manager", "Automatic", "Running"),
    services.Service("Wdiservices.ServiceHost", "Diagnostic services.Service Host", "Manual", "Stopped"),
    services.Service("WdiSystemHost", "Diagnostic System Host", "Manual", "Running"),
    services.Service("WdNisSvc", "Windows Defender Antivirus Network Inspection services.Service", "Manual", "Running"),
    services.Service("Wecsvc", "Windows Event Collector", "Manual", "Stopped"),
    services.Service("WEPHOSTSVC", "Windows Encryption Provider Host services.Service", "Manual", "Stopped"),
    services.Service("wercplsupport", "Problem Reports and Solutions Control Panel Support", "Manual", "Stopped"),
    services.Service("WerSvc", "Windows Error Reporting services.Service", "Manual", "Stopped"),
    services.Service("WiaRpc", "Still Image Acquisition Events", "Manual", "Stopped"),
    services.Service("WinDefend", "Windows Defender Antivirus services.Service", "Automatic", "Running"),
    services.Service("WinHttpAutoProxySvc", "WinHTTP Web Proxy Auto-Discovery services.Service", "Manual", "Running"),
    services.Service("Winmgmt", "Windows Management Instrumentation", "Automatic", "Running"),
    services.Service("WinRM", "Windows Remote Management (WS-Management)", "Automatic", "Running"),
    services.Service("wisvc", "Windows Insider services.Service", "Manual", "Stopped"),
    services.Service("wlidsvc", "Microsoft Account Sign-in Assistant", "Manual", "Running"),
    services.Service("WLMS", "Windows Licensing Monitoring services.Service", "Automatic", "Running"),
    services.Service("wmiApSrv", "WMI Performance Adapter", "Manual", "Stopped"),
    services.Service("WMPNetworkSvc", "Windows Media Player Network Sharing services.Service", "Manual", "Stopped"),
    services.Service("WPDBusEnum", "Portable Device Enumerator services.Service", "Manual", "Stopped"),
    services.Service("Wpnservices.Service", "Windows Push Notifications System services.Service", "Automatic", "Running"),
    services.Service("WpnUserservices.Service_f9adc", "Windows Push Notifications User services.Service_f9adc", "Automatic", "Running"),
    services.Service("WSearch", "Windows Search", "Disabled", "Stopped"),
    services.Service("wuauserv", "Windows Update", "Manual", "Running"),
]
