---
- name: Run Windows Zero-Day Hardening Script
  hosts: windows
  gather_facts: no

  vars:
    script_name: zero.ps1
    remote_script_path: C:\Temp\zero.ps1

  tasks:
    - name: Ensure Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy zero.ps1 to remote host
      win_copy:
        src: ../../windows/zero.ps1
        dest: "{{ remote_script_path }}"

    - name: Run zero.ps1 hardening script
      win_powershell:
        script: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          & "{{ remote_script_path }}"
      register: script_output
      ignore_errors: yes

    - name: Display script output
      debug:
        var: script_output.output
      when: script_output.output is defined

    - name: Display any errors
      debug:
        var: script_output.error
      when: script_output.error is defined and script_output.error | length > 0

    - name: Clean up - Remove script from remote host
      win_file:
        path: "{{ remote_script_path }}"
        state: absent
      when: script_output is succeeded
